image: Visual Studio 2019

shallow_clone: true

platform:
  - x64

configuration:
  - Release

matrix:
  fast_finish: true

only_commits:
  files:
    - src/
    - vc14/
    - .appveyor.yml

install:
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - cd %APPVEYOR_BUILD_FOLDER%

before_build:  |
  vcpkg integrate install
  copy /y mk\portfile.cmake C:\tools\vcpkg\ports\openal-soft\
  vcpkg install boost-iostreams:x64-windows
  vcpkg install boost-asio:x64-windows
  vcpkg install boost-filesystem:x64-windows
  vcpkg install boost-system:x64-windows
  vcpkg install boost-variant:x64-windows
  vcpkg install boost-lockfree:x64-windows
  vcpkg install boost-uuid:x64-windows
  vcpkg install glew:x64-windows
  vcpkg install libvorbis:x64-windows
  vcpkg install libogg:x64-windows
  vcpkg install lua:x64-windows
  vcpkg install luajit:x64-windows
  vcpkg install openal-soft:x64-windows
  vcpkg install opengl:x64-windows
  vcpkg install physfs:x64-windows
  vcpkg install zlib:x64-windows

build:
  parallel: true
  # MSBuild verbosity level
  #verbosity: detailed

cache:
  - c:\tools\vcpkg\installed\ -> appveyor.yml
  - vc14\x64

after_build:
  - cmd: 7z a otclient.zip otclient.exe *.dll

artifacts:
  - path: otclient.exe
  - path: '*.dll'
  - path: otclient.zip
